### ISSUE TITLE
Validaciones

### ISSUE THREAD

**Issue by FeliIsra** [TheRightJoin/TPCupon2019#2]
Hola wacho, soy yo devuelta. Les hago una consulta, alguno tiene ganas de arrancar a hacer distintas validaciones ?
Como por ejemplo, que no se pueda crear un proveedor 2 veces, etc.
Estoy casi segudo de que si haces algo de eso, la base va a tirar error.
Mas que validarlo, habria que cachearlo no ?
Saludos, espero que alguno le meta. 
besos, y carinios.
Felo xoxoxoxoxox

**Comment by lucascheistwer** [comment]
jajajaj sos un salame amigo

**Comment by FeliIsra** [comment]
Doy por concludio este issue.

Salu2
